sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true

sonar.sources=auth-provider,cache-service,llm,llm-consumer,news-gateway,news-parser,scripts,web-frontend,.github/workflows
sonar.tests=cache-service,llm-consumer,news-gateway,news-parser,cypress

sonar.test.inclusions=**/*_test.go,cypress/**/*.cy.js
sonar.exclusions=**/node_modules/**,**/cypress/downloads/**,**/internal/application/mocks/**,**/mocks/**,**/__pycache__/**,**/*.pyc
sonar.coverage.exclusions=**/*_test.go,cypress/**,web-frontend/**,.github/**,scripts/**,**/cmd/**

sonar.go.coverage.reportPaths=coverage/cache-service.out,coverage/llm-consumer.out,coverage/news-gateway.out,coverage/news-parser.out
