server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /news/ {
    proxy_pass http://news-gateway:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location = /predict {
    proxy_pass http://llm-consumer:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
