// Code generated by MockGen. DO NOT EDIT.
// Source: cache_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "data-cleaner/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddArticle mocks base method.
func (m *MockStorage) AddArticle(ctx context.Context, dto domain.ArticleDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddArticle", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddArticle indicates an expected call of AddArticle.
func (mr *MockStorageMockRecorder) AddArticle(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddArticle", reflect.TypeOf((*MockStorage)(nil).AddArticle), ctx, dto)
}

// AddLLMResponse mocks base method.
func (m *MockStorage) AddLLMResponse(ctx context.Context, dto domain.LLMResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLLMResponse", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLLMResponse indicates an expected call of AddLLMResponse.
func (mr *MockStorageMockRecorder) AddLLMResponse(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLLMResponse", reflect.TypeOf((*MockStorage)(nil).AddLLMResponse), ctx, dto)
}

// AddNews mocks base method.
func (m *MockStorage) AddNews(ctx context.Context, dto domain.NewsDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNews", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNews indicates an expected call of AddNews.
func (mr *MockStorageMockRecorder) AddNews(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNews", reflect.TypeOf((*MockStorage)(nil).AddNews), ctx, dto)
}
