// Code generated by MockGen. DO NOT EDIT.
// Source: app.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "news-parser/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRequestHandler is a mock of RequestHandler interface.
type MockRequestHandler struct {
	ctrl     *gomock.Controller
	recorder *MockRequestHandlerMockRecorder
}

// MockRequestHandlerMockRecorder is the mock recorder for MockRequestHandler.
type MockRequestHandlerMockRecorder struct {
	mock *MockRequestHandler
}

// NewMockRequestHandler creates a new mock instance.
func NewMockRequestHandler(ctrl *gomock.Controller) *MockRequestHandler {
	mock := &MockRequestHandler{ctrl: ctrl}
	mock.recorder = &MockRequestHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestHandler) EXPECT() *MockRequestHandlerMockRecorder {
	return m.recorder
}

// DoDataRequest mocks base method.
func (m *MockRequestHandler) DoDataRequest(url string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoDataRequest", url)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoDataRequest indicates an expected call of DoDataRequest.
func (mr *MockRequestHandlerMockRecorder) DoDataRequest(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoDataRequest", reflect.TypeOf((*MockRequestHandler)(nil).DoDataRequest), url)
}

// DoNewsRequest mocks base method.
func (m *MockRequestHandler) DoNewsRequest(category domain.Category) (domain.Articles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoNewsRequest", category)
	ret0, _ := ret[0].(domain.Articles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoNewsRequest indicates an expected call of DoNewsRequest.
func (mr *MockRequestHandlerMockRecorder) DoNewsRequest(category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoNewsRequest", reflect.TypeOf((*MockRequestHandler)(nil).DoNewsRequest), category)
}

// MockLLMNotifier is a mock of LLMNotifier interface.
type MockLLMNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockLLMNotifierMockRecorder
}

// MockLLMNotifierMockRecorder is the mock recorder for MockLLMNotifier.
type MockLLMNotifierMockRecorder struct {
	mock *MockLLMNotifier
}

// NewMockLLMNotifier creates a new mock instance.
func NewMockLLMNotifier(ctrl *gomock.Controller) *MockLLMNotifier {
	mock := &MockLLMNotifier{ctrl: ctrl}
	mock.recorder = &MockLLMNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMNotifier) EXPECT() *MockLLMNotifierMockRecorder {
	return m.recorder
}

// StartLLMPrediction mocks base method.
func (m *MockLLMNotifier) StartLLMPrediction() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartLLMPrediction")
	ret0, _ := ret[0].(error)
	return ret0
}

// StartLLMPrediction indicates an expected call of StartLLMPrediction.
func (mr *MockLLMNotifierMockRecorder) StartLLMPrediction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartLLMPrediction", reflect.TypeOf((*MockLLMNotifier)(nil).StartLLMPrediction))
}
